name: Monitor Main Website

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check Website Status
        run: |
          START_TIME=$(date +%s)
          RESPONSE=$(curl -Is -w "%{http_code}" -o /dev/null https://securenimbus.cloud)
          END_TIME=$(date +%s)
          RESPONSE_TIME=$((END_TIME - START_TIME))
          echo "Checked at $(date '+%Y-%m-%d %H:%M:%S %Z') IST equivalent: $(date -d '5 hours 30 minutes' '+%Y-%m-%d %H:%M:%S IST')"
          echo "HTTP Status: $RESPONSE"
          echo "Response Time: ${RESPONSE_TIME} seconds"
          if [ "$RESPONSE" != "200" ]; then
            echo "Website is down! HTTP Status: $RESPONSE"
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"content\": \"🚨 Website https://www.securenimbus.cloud is down! HTTP Status: $RESPONSE at $(date '+%Y-%m-%d %H:%M:%S %Z')\"}" \
              ${{ secrets.DISCORD_WEBHOOK_URL }}
            exit 1
          else
            echo "Website is up! HTTP Status: $RESPONSE"
          fi
        env:
          WEBSITE_URL: https://www.securenimbus.cloud
